version: '3.2'
services:
    lapone:
        build: .
        container_name: ${PREFIX_CONTAINER-}lapone-8.0
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - '${WEBPORT-8040}:80'
        links:
            - 'dblapone:database'
    dblapone:
        image: postgres:latest
        container_name: ${PREFIX_CONTAINER-}pglapone-8.0
        ports:
            - '${DBPORT-5433}:5432'
        environment:
            POSTGRES_USER: ${DBUSER-admin}
            POSTGRES_PASSWORD: ${DBPASS-password}
        volumes:
            - data_lapone:/var/lib/postgresql/data:rw
volumes:
    data_lapone:
